global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'billflow-gateway'
    static_configs:
      - targets: ['billflow-gateway:8080']
    metrics_path: '/metrics'

  - job_name: 'billflow-invoice'
    static_configs:
      - targets: ['billflow-invoice:8080']
    metrics_path: '/metrics'

  - job_name: 'billflow-tenant'
    static_configs:
      - targets: ['billflow-tenant:8080']
    metrics_path: '/metrics'

  - job_name: 'billflow-identity'
    static_configs:
      - targets: ['billflow-identity:8080']
    metrics_path: '/metrics'

  - job_name: 'billflow-customer'
    static_configs:
      - targets: ['billflow-customer:8080']
    metrics_path: '/metrics'

  - job_name: 'billflow-notification'
    static_configs:
      - targets: ['billflow-notification:8080']
    metrics_path: '/metrics'